# This is a basic workflow to help you get started with Actions

name: Lint, Test and Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VUE_APP_GIHPY_API_KEY: ${{ secrets.VUE_APP_GIHPY_API_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # setup the repository in the runner
      - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install # will run `npm install` command
      - name: Lint Run
        run: npm run lint # will run `npm run lint` command
      - name: Unit Test Run
        run: npm run test:unit # will run `npm run test:unit` command
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config-file: cypress.json
          spec: "tests/e2e/**/*"
        env:
          CYPRESS_baseUrl: http://localhost:8080/
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: Cypress-report-coverage
          path: tests/e2e/videos/*

  build:
     needs: [lint-and-test]
     runs-on: ubuntu-latest
     steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Setup Node.js # setup Node.js in the runner
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies and Pwa Generate
        run: |
          npm install -g @vue/cli 
          npm ci
          npm run pwa-icon-generate
        env:
          NODE_ENV: production
      - name: Build Project
        run: |
          npm run build --production
        env:
          NODE_ENV: production
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
